# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37dd09abd6c9e69d5e54e79c1336360b20bcfdd1ed41e614fa8169e74098ee6b5faa2c81917e56106dd9b15a036f027f5921bb4a3aec3f234550ac69815cd783

test:
  secret_key_base: f7d222ad93aa14817c707e2aca0e7fb8e14c5f79674e99dfb9f143bd41c183ffbd9703c2d6e5311a9e915cd4499bd91398f57d241f35cbf0b00152a84d095f38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
